module.exports = {
  testEnvironment: 'jsdom',
  testMatch: ['**/__tests__/**/*.test.js', '**/__tests__/**/*.test.jsx'],
  setupFilesAfterEnv: ['<rootDir>/src/__tests__/setup.js'],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '\\.(css|less|scss|sass)$': 'identity-obj-proxy',
    '^../../renderer/i18n/translations$': '<rootDir>/src/renderer/i18n/translations.js',
    '^../../renderer/i18n/LocaleProvider$': '<rootDir>/src/renderer/i18n/LocaleProvider.jsx',
    '^../../renderer/components/Toast$': '<rootDir>/src/renderer/components/Toast.jsx',
    '^../../renderer/components/Modal$': '<rootDir>/src/renderer/components/Modal.jsx',
    '^../../../src/db/database$': '<rootDir>/src/db/database.js',
    '^../../../src/main/logger$': '<rootDir>/src/main/logger.js',
    '^../../../src/db/repositories/(.*)$': '<rootDir>/src/db/repositories/$1.js',
    '^../../shared/store$': '<rootDir>/src/shared/store.js',
    '^../../renderer/logger$': '<rootDir>/src/renderer/logger.js',
    '^src/db/database$': '<rootDir>/src/db/database.js',
    '^src/main/logger$': '<rootDir>/src/main/logger.js',
    '^src/db/repositories/(.*)$': '<rootDir>/src/db/repositories/$1.js',
    '^src/renderer/i18n/translations$': '<rootDir>/src/renderer/i18n/translations.js',
    '^src/renderer/i18n/LocaleProvider$': '<rootDir>/src/renderer/i18n/LocaleProvider.jsx',
    '^src/renderer/components/Toast$': '<rootDir>/src/renderer/components/Toast.jsx',
    '^src/renderer/components/Modal$': '<rootDir>/src/renderer/components/Modal.jsx',
    '^src/renderer/components/DataTable$': '<rootDir>/src/renderer/components/DataTable.jsx',
    '^src/renderer/components/ConfirmModal$': '<rootDir>/src/renderer/components/ConfirmModal.jsx',
    '^src/renderer/components/ActivityTimeline$': '<rootDir>/src/renderer/components/ActivityTimeline.jsx',
    '^src/renderer/components/GlobalSearch$': '<rootDir>/src/renderer/components/GlobalSearch.jsx',
    '^src/shared/store$': '<rootDir>/src/shared/store.js',
    '^src/renderer/logger$': '<rootDir>/src/renderer/logger.js',
  },
  transform: {
    '^.+\\.(js|jsx)$': 'babel-jest',
  },
  transformIgnorePatterns: [
    '/node_modules/(?!(electron|@electron)/)',
  ],
  moduleFileExtensions: ['js', 'jsx'],
  moduleDirectories: ['node_modules', 'src'],
  collectCoverageFrom: [
    'src/**/*.{js,jsx}',
    '!src/main/main.js',
    '!src/renderer/index.jsx',
    '!src/__tests__/**/*',
  ],
  coverageThreshold: {
    global: {
      branches: 10,
      functions: 10,
      lines: 10,
      statements: 10,
    },
  },
  testTimeout: 10000,
};
